trigger:
  branches:
    include:
      - main  # Branche sur laquelle la pipeline sera déclenchée

pool:
  name: hkAgent_pool  # L'agent pool que tu as configuré

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: |
    echo Hello, World!
  displayName: 'Run a one-line script'
