trigger:
  branches:
    include:
      - main  # Déclenchement automatique sur la branche main

pool:
  name: hkAgent_pool  # L'agent pool personnalisé

stages:
  # ------------- STAGE CI (Build) -------------
  - stage: Build
    displayName: 'Build Application'
    jobs:
      - job: BuildJob
        displayName: 'Build and Publish'
        steps:
          - task: UseDotNet@2
            inputs:
              packageType: 'sdk'
              version: '6.x'
              installationPath: $(Agent.ToolsDirectory)/dotnet

          - script: |
              dotnet restore
              dotnet publish -c Release -o $(Build.ArtifactStagingDirectory)
            displayName: 'Dotnet Restore, Build, Publish'

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'
              publishLocation: 'Container'
            displayName: 'Publier artefacts du build'

  # ------------- STAGE CD (Déploiement en Production) -------------
  - stage: Deploy_Production
    displayName: 'Déploiement en Production'
    dependsOn: Build  # Doit dépendre d'un stage existant
    condition: succeeded()
    jobs:
      - deployment: DeployProduction
        displayName: 'Deploy to Production'
        environment: production
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureWebApp@1
                  inputs:
                    azureSubscription: 'Nom exact de ta connexion Azure'
                    appType: 'webApp'  # Type d'application
                    appName: 'Nom_App_Service_Production'  # Remplace avec le nom réel de ton App Service
                    package: '$(Pipeline.Workspace)/drop/*.zip'
